### ISSUE TITLE
create CRD on pipeline location 

### ISSUE THREAD

**Issue by goern** [thoth-station/meteor-operator#102]
## Problem statement
There are multiple ways to maintain the pipeline/task declarations required by the operator, lets document where we put them and why

## High-level Goals
CRD documenting our arch decision

## Proposal description
1. keep the pipeline/task declaration yamls in the operator at `config/tekon` so that they are deployed via customize during `make deploy`

### Alternatives
2. keep them in a separate repo or dir with kustomize being able to deploy them
3. put them in a helm chart

### Additional context
n/a

## Acceptance Criteria

- [ ] CRD committed to meteor-operator repo

**Comment by codificat** [comment]
I'm pretty sure that the references to "CRD" here actually meant "ADR".

The ADR for how to package the pipeline task definitions was provided by https://github.com/thoth-station/opendatahub-cnbi/pull/29 and is now available at https://github.com/thoth-station/opendatahub-cnbi/blob/main/docs/decisions/0002-deploy-pipelines.md

/close
