### ISSUE TITLE
add odh label

### ISSUE THREAD

**Issue by goern** [thoth-station/meteor-operator#155]
As Gage pointed out in chat, we need to add another label 'opendatahub.io/notebook-name: true' to the imagestream created by CRE

/kind feature
/wg cre
/priority critical-urgent

**Comment by goern** [comment]
#124 might be related and fix this

**Comment by harshad16** [comment]
Already being added on built image: https://github.com/thoth-station/meteor-operator/blob/a60a8ac5f4bdc0db7964b53c6cf267ec02fbf270/pipelines/pipelines/cre-package-list.yaml#L94

Missing in import:
- [] https://github.com/thoth-station/meteor-operator/blob/a60a8ac5f4bdc0db7964b53c6cf267ec02fbf270/pipelines/pipelines/cre-import.yaml#L63

**Comment by codificat** [comment]
Actually, on import this label is also added - but only after the validation of the image succeeds: https://github.com/thoth-station/meteor-operator/blob/a60a8ac5f4bdc0db7964b53c6cf267ec02fbf270/pipelines/pipelines/cre-import.yaml#L174-L177
