### ISSUE TITLE
gitRepo build pipeline is not working

### ISSUE THREAD

**Issue by codificat** [thoth-station/meteor-operator#162]
## Bug description

The current version of the `cre-gitrepo` pipeline (that implements the `GitRepository` build type) is not working.

### Steps to Reproduce
1. Create a CustomRuntimeEnvironment of type `GitRepository` (for example, the one in [config/samples](https://github.com/thoth-station/meteor-operator/blob/825a2519425ada316d545ba8b2b4b60d2168b4bb/config/samples/meteor_v1alpha1_customruntimeenvironment_git-repository.yaml))
2. Check the related PipelineRun
3. See error

### Actual behavior

```
$ tkn pr describe -L
Name:              cre-elyra-aidevsecops-tutorial-gitrepo
Namespace:         aicoe-meteor
Pipeline Ref:      cre-gitrepo
Service Account:   pipeline
Timeout:           1h0m0s
Labels:
 cre.thoth-station.ninja/pipeline=gitrepo
 tekton.dev/pipeline=cre-gitrepo

🌡️  Status

STARTED         DURATION    STATUS
5 seconds ago   0 seconds   Failed(InvalidTaskResultReference)

💌 Message

invalid pipeline result "url": referenced pipeline task "url-to-results" does not exist

⚓ Params

 NAME            VALUE
 ∙ name          Elyra DevSecOps Tutorial
 ∙ creator       codificat
 ∙ description   Build from the Elyra Tutorial
 ∙ url           https://github.com/AICoE/elyra-aidevsecops-tutorial
 ∙ ref           master

📂 Workspaces

 NAME           SUB PATH   WORKSPACE BINDING
 ∙ data         ---        VolumeClaimTemplate
 ∙ sslcertdir   ---        ConfigMap (config=openshift-service-ca.crt,item=service-ca.crt=ca.crt)
```

### Expected behavior

The PipelineRun created for the git repo CRE works.

### Environment information

meteor-operator v0.2.1

### Additional context

Noticed this while reviewing https://github.com/thoth-station/odh-dashboard/pull/14

This is not a use case in the initial CNBi functionality, and therefore it's optional in that sense for the initial version.

**Comment by VannTen** [comment]
Is the pipeline results used somewhere ? Can't figure out what should be there (and blame is not helpful, too much renaming)

**Comment by codificat** [comment]
> Is the pipeline results used somewhere ? 

It isn't.

> Can't figure out what should be there
> (and blame is not helpful, too much renaming)

Yep. To hopefully clarify a bit: the pipeline and tasks came mostly "as is" from meteor's jupyterhub pipelines, as hosted in the [helm charts repo](https://github.com/thoth-station/helm-charts/blob/08e78c0bd12cfe85cad65d5d1b6979ddb45ee1fb/charts/meteor-pipelines/templates/meteor_jupyterhub.yaml)

There are a few things we don't use at the moment: results, owner ref, and namespace extraction.

**Comment by VannTen** [comment]
As an alternative, I also have #152 as a possible alternative (==
PackageList + a PEP 517 build and install).

**Comment by codificat** [comment]
> As an alternative, I also have #152 as a possible alternative (== PackageList + a PEP 517 build and install).

Apologies if I am missing something here, but I believe #152 is complementary rather than alternative.

> This intend to implement a git-repo pipeline which would not depend on an aicoe-ci.yaml file at the repository root.

Basic question about the scope here, just want to clarify.

The proposal here would aim at building images for git repos that host Python packages, correct?  And (probably) not cover repos that contain (mostly) jupyter notebooks, right?

I'm asking because I believe CNBi / CRE's main use case is for repos where (most of) the content is "notebook-type" rather than Python packages.

**Comment by VannTen** [comment]
On Mon, Jan 16, 2023 at 04:58:02AM -0800, Pep Turró Mauri wrote:
> > As an alternative, I also have #152 as a possible alternative (== PackageList + a PEP 517 build and install).
> 
> Apologies if I am missing something here, but I believe #152 is complementary rather than alternative.
> 
> > This intend to implement a git-repo pipeline which would not depend on an aicoe-ci.yaml file at the repository root.
> 
> Basic question about the scope here, just want to clarify.
> 
> The proposal here would aim at building images for git repos that host Python packages, correct?  And (probably) not cover repos that contain (mostly) jupyter notebooks, right?
> 
> I'm asking because I believe CNBi / CRE's main use case is for repos where (most of) the content is "notebook-type" rather than Python packages.

So the current gitRepo is for git repos containing notebooks in Python ?
I had not get that ^^
