### ISSUE TITLE
restructure config/ so that it could be used via kfdef

### ISSUE THREAD

**Issue by goern** [thoth-station/meteor-operator#88]
SSIA so that we can deploy the meteor-operator as part of an ODH deployment.

/kind feature
/priority critical-urgent

**Comment by goern** [comment]
I'm unsure what needs to be done here. @codificat can you outline?

/assign @codificat 
/wg cnbi

**Comment by goern** [comment]
Related-To: https://github.com/thoth-station/opendatahub-cnbi/issues/20

**Comment by harshad16** [comment]
On going through the operator framework 
the framework https://sdk.operatorframework.io/docs/building-operators/golang/quickstart/ , creates the pattern of the `config` directory with all the Kustomization.yaml 
Changing the structure would require changes in Makefile, which releases the operator.

**Comment by goern** [comment]
I think that is ok, it will just make SDK updates harder. what about creating an additional manifest directory for the customizations we need for ODH, op1st? So that we separate the SDK behavior and requirements from deployment-related file.
